In [22]:
import pandas as pd 
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, LogisticRegression, BayesianRidge
import pickle

In [23]:
gt = pd.read_csv('final_csv_files/hero_xyz_20Hz.csv')
gt.columns = ['time','x','y','z']
df = pd.read_csv('final_csv_files/cam_lidar_xyz_20Hz.csv')
df.columns = ['time','cam_x','cam_y','cam_z', 'lid_x', 'lid_y', 'lid_z']

In [24]:
X = np.asarray(df[['cam_x', 'cam_y', 'cam_z', 'lid_x', 'lid_y', 'lid_z']])
Y = np.asarray(gt[['x', 'y', 'z']])

In [25]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, shuffle=True)

In [26]:
lr = LinearRegression()

lr.fit(X_train, Y_train)
print('Score: ', lr.score(X_test, Y_test))
print('Weights: ', lr.coef_)

Score:  0.999835887489264
Weights:  [[ 0.28246403 -0.05867583 -0.36629552  0.72270332 -0.01343519  0.12159045]
 [-0.17191241  1.12527304  2.28791574  0.17354541 -0.07202553 -2.30308823]
 [ 0.00847683 -0.01748432 -0.2503942  -0.00780808  0.01177237  1.21821204]]


In [27]:
lr.predict([[15.0639328276075,-109.610933453907,1.15454667017099,15.4335601199163,-110.334714233467,1.05167628657328]])

array([[  10.23331882, -104.29806649,   -0.31627158]])

In [28]:
filename = 'lr_model.sav'
pickle.dump(lr, open(filename, 'wb'))

In [29]:
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.score(X_test, Y_test)

pred_Y = loaded_model.predict(X)